FROM postgres:17.2-alpine

# ENV POSTGRES_DB=db \
#    POSTGRES_USER=usr \
#    POSTGRES_PASSWORD=pwd
# Copier les fichiers SQL dans le dossier spécial de Postgres
COPY docker-entrypoint-initdb/ /docker-entrypoint-initdb.d/