#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/docker_network

# roles/docker_network/tasks/main.yml
- name: Create Docker network
  docker_network:
    name: app-network
    state: present
    driver: bridge
