- name: Load env variables from YAML file
  include_vars:
    file: "{{ playbook_dir }}/env_vars.yml"
    name: postgres_env
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Run PostgreSQL container
  docker_container:
    name: my_postgres
    image: kamelia762/tp-devops-database
    networks:
      - name: app-network
    env:
      POSTGRES_USER: "{{ postgres_env.POSTGRES_USER }}"
      POSTGRES_PASSWORD: "{{ postgres_env.POSTGRES_PASSWORD }}"
      POSTGRES_DB: "{{ postgres_env.POSTGRES_DB }}"
    state: started
    restart_policy: always
