#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/proxy

# roles/proxy/tasks/main.yml

# roles/httpd/tasks/main.yml
- name: Launch HTTP server container
  docker_container:
    name: httpd
    image: httpd:latest
    state: started
    published_ports:
      - "80:80"
    networks:
      - my-network
